base_llm: meta/llama-3.1-70b-instruct
max_token_num: 2048
member_num: 3
related_paper_num: 5
return_num: 1
reviewer_num: 1
stream: null
temperature: 0.6
top_p: null
write_proposal_strategy: default
max_env_run_num: 1
proposal_num: 1
use_rag: True
